print('Здравствуй, мир!')
print('Как тебя зовут?')
name = input()
print('Рад познакомиться, ' + name)
print('Длина твоего имени:')
print(len(name), ' буквы')
print('Сколько тебе лет?')
Age = input()
print("Черзе год тебе будет: " + str(int(Age) + 1) + ", лет")
